package:
  name: xcube_places_plugin
  version: 0.0.2

source:
  url: https://github.com/dcs4cop/xcube-geodb-places/archive/refs/tags/v0.0.2.tar.gz
  sha256: 2e4685530ee1d19cfb366456485d294dcb1c225bb34ecfec76c35e1f5be4046e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - xcube >=1.2.0
    - xcube_geodb
    - requests
    - python-fastjsonschema

test:
  imports:
    - xcube_places_plugin 

about:
  summary: xcube_places_plugin allows to load features from geoDB as xcube places
  home: https://github.com/dcs4cop/xcube-geodb-places
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: xcube_places_plugin allows to load features from geoDB as xcube places

extra:
  recipe-maintainers:
    - thomasstorm
