package:
  name: xcube_places_plugin
  version: 0.0.4

source:
  url: https://github.com/dcs4cop/xcube-geodb-places/archive/refs/tags/v0.0.4.tar.gz
  sha256: 65abde603a67df65cb5b9cd6b022c323f1eb691fd450602a33517431db7008ed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - xcube >=1.2.0
    - xcube_geodb
    - requests
    - python-fastjsonschema

test:
  imports:
    - xcube_places_plugin 

about:
  summary: xcube_places_plugin allows to load features from geoDB as xcube places
  home: https://github.com/xcube-dev/xcube-geodb-places
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: xcube_places_plugin allows to load features from geoDB as xcube places

extra:
  recipe-maintainers:
    - thomasstorm
    - TonioF
